baseURL = "https://hakam.netlify.com"
title = "Hakamatsuri"

languageCode = "id"  # for the RSS generation
defaultContentLanguage = "id"

[permalinks]
posts = "/blog/:title/"
lirik = "/lirik/:title/"

enableRobotsTXT = true

# Enable Disqus
# disqusShortname = "XXX"

# Google Analytics
# googleAnalytics = "UA-123-45"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
style = "light"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
dateFormat = "02 Jan 2006"  # if unset, default is "2006-01-02"
readingTime = true  # show reading time after article date
logo = "/img/logo.png"  # if you have a logo png
description = "Blog personal yang berisi catatan dan ke-random-an seorang manusia"
author = "Hakam"
fullRss = false # Puts entire HTML post into rss 'description' tag. If unset, default is false.

[params.assets]
# css = ["css/fonts.css"]

[params.comments]
enable = false  # En/Disable comments globally, default: false. You can always enable comments on per page.

[params.nav]
showCategories = true       # /categories/
showTags = true            # /tags/
showAbout = true            # /about/

# custom navigation items
# [[params.nav.custom]]
# title = ""
# url = ""